/* eslint-disable max-len */
import { nanoid } from '@reduxjs/toolkit';

const staticData = [
  {
    dateModified: '2016-11-12 15:10:54',
    idDrink: '13198',
    strAlcoholic: 'Alcoholic',
    strCategory: 'Shot',
    strCreativeCommonsConfirmed: 'No',
    strDrink: 'Quick F**K',
    strDrinkAlternate: null,
    strDrinkThumb:
      'https://www.thecocktaildb.com/images/media/drink/wvtwpp1478963454.jpg',
    strGlass: 'Shot glass',
    strIBA: null,
    strImageAttribution: null,
    strImageSource: null,
    strIngredient1: 'Kahlua',
    strIngredient2: 'Midori melon liqueur',
    strIngredient3: 'Baileys irish cream',
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strInstructions:
      "In a shot glass add 1/3 Kahlua first. Then 1/3 Miduri, topping it off with a 1/3 bailey's irish cream",
    strInstructionsDE:
      "In einem Schnapsglas zuerst 1/3 Kahlua geben. Dann 1/3 Miduri, ergänzt durch 1/3 Bailey's irish Cream.",
    strInstructionsES: null,
    strInstructionsFR: null,
    strInstructionsIT:
      'In un bicchierino aggiungere prima 1/3 di Kahlua.\r\nQuindi 1/3 di Midori, completando con 1/3 di crema irlandese di bailey',
    strInstructionsZH_HANS: null,
    strInstructionsZH_HANT: null,
    strMeasure1: '1 part ',
    strMeasure2: '1 part ',
    strMeasure3: '1 part ',
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strTags: null,
    strVideo: null,
  },
  {
    dateModified: '2016-09-06 23:41:03',
    idDrink: '11288',
    strAlcoholic: 'Alcoholic',
    strCategory: 'Ordinary Drink',
    strCreativeCommonsConfirmed: 'Yes',
    strDrink: 'Cuba Libre',
    strDrinkAlternate: null,
    strDrinkThumb:
      'https://www.thecocktaildb.com/images/media/drink/wmkbfj1606853905.jpg',
    strGlass: 'Highball glass',
    strIBA: 'Contemporary Classics',
    strImageAttribution: 'Martin Belam (currybet)',
    strImageSource: 'https://commons.wikimedia.org/wiki/File:Cuba_Libre.jpg',
    strIngredient1: 'Light rum',
    strIngredient2: 'Lime',
    strIngredient3: 'Coca-Cola',
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strInstructions:
      'Build all ingredients in a Collins glass filled with ice. Garnish with lime wedge.',
    strInstructionsDE:
      'Geben Sie alle Zutaten in ein mit Eis gefülltes Collins-Glas. Mit Limettenkeil garnieren.',
    strInstructionsES: null,
    strInstructionsFR: null,
    strInstructionsIT:
      'Mettere tutti gli ingredienti in un bicchiere Collins pieno di ghiaccio. Guarnire con uno spicchio di lime.',
    strInstructionsZH_HANS: null,
    strInstructionsZH_HANT: null,
    strMeasure1: '2 oz ',
    strMeasure2: 'Juice of 1/2 ',
    strMeasure3: null,
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strTags: 'IBA,ContemporaryClassic',
    strVideo: null,
  },
  {
    dateModified: '2016-11-12 15:10:54',
    idDrink: nanoid(),
    strAlcoholic: 'Alcoholic',
    strCategory: 'Shot',
    strCreativeCommonsConfirmed: 'No',
    strDrink: 'Quick F**K',
    strDrinkAlternate: null,
    strDrinkThumb:
      'https://www.thecocktaildb.com/images/media/drink/wvtwpp1478963454.jpg',
    strGlass: 'Shot glass',
    strIBA: null,
    strImageAttribution: null,
    strImageSource: null,
    strIngredient1: 'Kahlua',
    strIngredient2: 'Midori melon liqueur',
    strIngredient3: 'Baileys irish cream',
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strInstructions:
      "In a shot glass add 1/3 Kahlua first. Then 1/3 Miduri, topping it off with a 1/3 bailey's irish cream",
    strInstructionsDE:
      "In einem Schnapsglas zuerst 1/3 Kahlua geben. Dann 1/3 Miduri, ergänzt durch 1/3 Bailey's irish Cream.",
    strInstructionsES: null,
    strInstructionsFR: null,
    strInstructionsIT:
      'In un bicchierino aggiungere prima 1/3 di Kahlua.\r\nQuindi 1/3 di Midori, completando con 1/3 di crema irlandese di bailey',
    strInstructionsZH_HANS: null,
    strInstructionsZH_HANT: null,
    strMeasure1: '1 part ',
    strMeasure2: '1 part ',
    strMeasure3: '1 part ',
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strTags: null,
    strVideo: null,
  },
  {
    dateModified: '2016-09-06 23:41:03',
    idDrink: nanoid(),
    strAlcoholic: 'Alcoholic',
    strCategory: 'Ordinary Drink',
    strCreativeCommonsConfirmed: 'Yes',
    strDrink: 'Cuba Libre',
    strDrinkAlternate: null,
    strDrinkThumb:
      'https://www.thecocktaildb.com/images/media/drink/wmkbfj1606853905.jpg',
    strGlass: 'Highball glass',
    strIBA: 'Contemporary Classics',
    strImageAttribution: 'Martin Belam (currybet)',
    strImageSource: 'https://commons.wikimedia.org/wiki/File:Cuba_Libre.jpg',
    strIngredient1: 'Light rum',
    strIngredient2: 'Lime',
    strIngredient3: 'Coca-Cola',
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strInstructions:
      'Build all ingredients in a Collins glass filled with ice. Garnish with lime wedge.',
    strInstructionsDE:
      'Geben Sie alle Zutaten in ein mit Eis gefülltes Collins-Glas. Mit Limettenkeil garnieren.',
    strInstructionsES: null,
    strInstructionsFR: null,
    strInstructionsIT:
      'Mettere tutti gli ingredienti in un bicchiere Collins pieno di ghiaccio. Guarnire con uno spicchio di lime.',
    strInstructionsZH_HANS: null,
    strInstructionsZH_HANT: null,
    strMeasure1: '2 oz ',
    strMeasure2: 'Juice of 1/2 ',
    strMeasure3: null,
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strTags: 'IBA,ContemporaryClassic',
    strVideo: null,
  },
];

export default staticData;
